version: '3.8'

services:
  parser-bot:
    build: .
    container_name: AiBiographer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./:/app

  web-uploader:
    build: .
    container_name: AiBiographer_Web
    restart: unless-stopped
    command: python -u main.py web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./:/app
